### ISSUE TITLE
Release file confusement.

### ISSUE THREAD

**Issue by noahtrr** [Lost-Entrepreneur439/thinkpad-t480s-hackintosh#10]
According to your 2.0 release which would be the only one for MacOS Sonoma, the EFI folder contains the wrong files.

Would you be able to upload the right EFI Folder, I'd love to use the prebuilt stuff.

**Comment by Lost-Entrepreneur439** [comment]
I don't support my EFIs anymore. Even if you were able to download it, it's likely it wouldn't work with the latest version of Sonoma and it's very outdated. Build your own EFI using the Dortania guide.

**Comment by noahtrr** [comment]
Alright then, thanks for the clarification, I'll try.
