### ISSUE TITLE
sleep/wake up problem

### ISSUE THREAD

**Issue by lioneliio** [Lost-Entrepreneur439/thinkpad-t480s-hackintosh#2]
Really thanks for the bulid. But I’ve got some problems here.I’m with the V1.1.1 release.

1. The startup took a loooooong time. When the progress bar reaches halfway, it seems totally stopped, like 60 seconds or more, then it goes on and finish startup. It’s not a big problem, but it would be really nice to have it fixed.
2. Bluetooth seems not working. It can scan my mouse(M800Pro) though bluetooth and connect to it. But the mouse can not move a bit.
3. Can not wake up after sleep. After automatic sleep, it can not be woken up in any way, no matter the keyboards, the wired mouse, or the power button. The only way I can do is long press the power button to shut down and startup again. 

* I've used one-key-hidpi (https://github.com/xzhih/one-key-hidpi) to improve display. Don't know if it effects.

**Comment by Lost-Entrepreneur439** [comment]
Not sure about the startup issue, I don't have that, bluetooth issue seems like an issue with your mouse, the sleep issue is related to one-key-hidpi.

**Comment by lioneliio** [comment]
Any suggestions for the startup problem? 
After a long restart it shows 「开机出现了问题，是否需要恢复打开的窗口 something wrong in the startup progress, whether to restore open windows, yes or no」 It seems something went wrong during shutdown.

**Comment by lioneliio** [comment]
1. After some research,  just delete some 「Sleep Wake Failure...」 files in CONSOLE app, the 「The computer shut down because a problem occurred」 problem was fixed. 
2. Also the can not wake up problem followed step 1 was disappeared too!
3. Now the startup progress seems normal, so I will keep the「-v」in boot-args, that's not a big deal, I can accept.

Thanks for the bulid again.

**Comment by Lost-Entrepreneur439** [comment]
You may be able to remove -v now, I've had a similar issue on my Dell Latitude E6530 a few times where about half way through the boot process it'll just reboot, and it can be fixed by just adding -v to the boot-args, booting, and then removing -v and booting again.

**Comment by lioneliio** [comment]
I've tried, and it works.Also upgrade the BIOS to 1.54 helps too.

**Comment by FlashTang** [comment]
> I've tried, and it works.Also upgrade the BIOS to 1.54 helps too.

你好，你笔记本型号是t480s吗？我这里也是无法唤醒，请问是怎么解决的？
