### ISSUE TITLE
Fan Control not possible

### ISSUE THREAD

**Issue by davidohne** [Lost-Entrepreneur439/thinkpad-t480s-hackintosh#4]
Thank you for your nice work! Everythink worked quite well on my side.
Unfortunately my T480S is a little bit loud. I've got the 8350u cpu and I'm undervolting with voltageshift -129 which works fine at the moment. 

I found a way to get RW access to the EC by adding the SSDT-YogaSMC and SSDT-EC from: https://github.com/RXyzDevelopment/T480S-OC/tree/Ventura/ACPI

But I still can't use Mac Fan Control or TG Pro. Do you have any idea how we can manipulate the fan control settings, so the device doesn't spin the fan on short cpu 

best,
David

Edit:
Okay: I think I can control the fan speed in the YogaSMCNC.

**Comment by davidohne** [comment]
Something else: How is your trackpad working in terms of moving items and files around. It always "stopps" beeing pushed and looses the file/item.. That's quite annoying. I'm thinking about changing it to the yoga 3 glass trackpad, but I don't know if this will fix the problem...

**Comment by Lost-Entrepreneur439** [comment]
I'm aware of the touchpad issue. The workaround I've discovered for now is using the top mouse buttons instead of the bottom mouse buttons.

**Comment by davidohne** [comment]
Ok. So my trackpad isn't broken.. 
Do you think changing the trackpad to a yoga 3 one (01LV554) could fix this behaviour?

**Comment by davidohne** [comment]
I added VodooRMI and I think it is more reliable now.. Will keep on testing.

**Comment by Lost-Entrepreneur439** [comment]
I tried switching to the version of VoodooSMBus included with VoodooRMI, and this did fix the issue with clicking and dragging, however it'll register every click with the bottom left click button as a force click, to fix that you will need to disable force clicking (System Settings -> Trackpad -> Turn off "Force Click and haptic feedback"). You don't need VoodooRMI itself, thats only for Synaptics touchpads, the T480s uses an Elan touchpad.
