### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by ellnic** [Lost-Entrepreneur439/thinkpad-t480s-hackintosh#6]
Firstly, thanks for putting this together. I'm not so active on the Hack scene at the moment and I don't have a lot of time, so this has saved me the faffing around).

I could PR these things but I'm still playing around with some stuff and haven't forked your repo yet so I'll just mention them here.

A couple of things I have noticed with your config (many of which I think @Hasodikis has implimented in a recent release), please take these as friendly input and not criticism 🙂 :

1. Your CPU never drops below about 1.25GHz, if you add CPU Friend that will allow it to drop to 800Mhz drawing about 1.8w at idle. (Hasodikis has gone even further and undervolted his too, something I might look at adding to mine at some point)

2. I mentioned this in the other issue, but if you change `<key>SyncRuntimePermissions</key>` to `<true/>` it allows Linux booting whilst not affecting macOS or Windows.

3. If you make use of the Thinkpad Assistant app, you can enable the rest of the Fn keys and get on screen prompts for them including the backlit keys.

4. If you change your SMBIOS to MacBookPro15,2 you'll get a quite a bit more performance:

Your vanilla MacBookPro14,1 (Without low power enabled):

![Screenshot 2023-09-13 at 17 47 09](https://github.com/Lost-Entrepreneur439/thinkpad-t480s-hackintosh/assets/16370944/5513e421-75f6-4bad-a8a9-6f743e588dc7)

Your vanilla but changed to MacBookPro15,2 (Without low power enabled)

![Screenshot 2023-09-14 at 11 13 09](https://github.com/Lost-Entrepreneur439/thinkpad-t480s-hackintosh/assets/16370944/8be21b7d-fd77-40f4-bf6a-ffc87de7aee8)

Your vanilla but changed to MacBookPro15,2 (With low power enabled)

![Screenshot 2023-09-14 at 11 09 35](https://github.com/Lost-Entrepreneur439/thinkpad-t480s-hackintosh/assets/16370944/c31d6b04-aeba-4d6c-b3d3-f91cf933b801)

:) happy hacking

**Comment by Hasodikis** [comment]
It is my understanding that Lost-Entrepreneur439 tries to keep his EFI simple. 

I on the other hand have a specifically for my needs tailored EFI. 

As a lawyer I edit documents and use a browser, which are both light tasks. I need no WWLAN or card reader or thunderbolt. 

However I do need the best battery life possible.

So: 
a) I undervolted C PU-iGPU -CPU cache and disabled turbo. 
b) I spent days on how to load a specific SSDT to enable lenovo thermal solution, an SSDT for usb power configuration kai an SSDT for Sleep (https://www.tonymacx86.com/threads/finaly-solved-thinkpad-t480s-macos13-5-1-oc-0-9-4-2-acpi-errors.326911/_).
c) I disabled card reader, thunderbolt, wwlan in BIOS. 
d) Finally, I replaced the original intel wifi/BT module, with a BCM94360NG. 

At the moment, power consumption at idle in PKG is bellow 1 watt! PKG is at around 0.60-0,70 watts! With screen at half brightness and BT off the battery is discharging with less than 4,3 Watts on idle. 

All these came at the expense of performance. And of course my time.....

**Comment by Lost-Entrepreneur439** [comment]
1. CPUFriend is unneeded for systems with working power management as far as I know, and power management is working for me.
2. I will be making that change in the next version of the EFI
3. I will look into ThinkpadAssistant and add it if it works for me
4. I personally got worse performance with MacBookPro15,2, however I will be keeping the 15,2 SMBIOS on my personal T480s and will be introducing it in a later release of the EFI, as 14,1 is being dropped in Sonoma.

**Comment by Hasodikis** [comment]
Thank you Ellnic. 
The lower score probably has to do with CPUFriendDataProvider kext which is geared towards the lowest possible performance. 

I did notice that to for the battery using a different app. I probably has to do with the ssdt's used. 

I haven' t give it much thought as of now. 

At the moment I am getting a bit more that 6 hours typing text in pages. 14 hours  is completely unrealistic even in Windows...

**Comment by Lost-Entrepreneur439** [comment]
@ellnic Yeah, maybe it's just because I have a different CPU, idk.

I've decided ThinkPadAssistant is not needed, everything it can do can be done with YogaSMCNC, which I am using and I prefer.

**Comment by ellnic** [comment]
One other thing I've done which I find really useful is map F13 to take a screenshot. F13 happens to be the PrtSc key.

In keyboard shortcuts, set your preference capture type to F13. I chose region, because you can hit the key then spacebar to grab the window instead:

![Screenshot 2023-09-14 at 15 20 28](https://github.com/Lost-Entrepreneur439/thinkpad-t480s-hackintosh/assets/16370944/a545bbde-5271-47fa-9f89-ff6199a4e42b)

Not really a Hackintosh thing, but useful to be able to use that key :)

**Comment by Hasodikis** [comment]
> @Hasodikis you've done a great job. I did fire up your EFI to see what it was like but the geekbench score was lower than I had hoped, which obviously aligns with your goals, but I tend to do a lot of computational tasks like compressing/uncompressing, compiling etc so for me I wanted a bit more.
> 
> Btw, when I was using your EFI, I also noticed that there was no remaining time estimate in the battery info like this:


I checked it and it works with battery monitor.
The 6 hours on my screenshot is due to the laptop staying idle or with minimal usage for a long time. But it seems to work. 

![image](https://github.com/Lost-Entrepreneur439/thinkpad-t480s-hackintosh/assets/61179177/fdedadc1-8b16-44ec-b7da-b23be70d973c)

**Comment by ellnic** [comment]
@Hasodikis that’s really good. ~6 hours at 88% is an amazing achievement. 👏

**Comment by Hasodikis** [comment]
But its not accurate because I had it seating at idle for many minutes. 
All these programs are not accurate unless you constantly perform your usual tasks. If you let the computer idle, they show increased remaining time. 

The real time is about 6 hours of typing in pages app with the screen at half brightness and BT off with a battery of 88% health. 

I find that satisfactory. its less than my t460 (which has two batteries and the external is a extended one), but still good.

**Comment by ellnic** [comment]
Yes, I understand this - but if I compare to my system which is sat idle (so like for like) at the same battery age and percentage, it’s about 3 hours 50 minutes. :-)

**Comment by Hasodikis** [comment]
Thats bad. Really bad. 
With my EFI?

**Comment by ellnic** [comment]
No, with Lost-Entrepreneur439’s with some changes.

**Comment by Hasodikis** [comment]
Then just test my EFI with a new CPUFriendDataProvider.kext for your performance needs. 

No other modifications for CPU performance are present in my EFI ( unless you enable an voltageshift service).
