### ISSUE TITLE
fixed trackpad stuttering problem

### ISSUE THREAD

**Issue by EliasGabr** [Lost-Entrepreneur439/thinkpad-t480s-hackintosh#9]
i think the https://github.com/VoodooSMBus/VoodooSMBus repo which is used got an update or something where there is a documented option called DisableTrackpad on Trackpoint, and the buttons above the trackpad are technically trackpoint buttons, so you just disable that option in the latest voodoosmbus release and it works smoothly

**Comment by EliasGabr** [comment]
yeah

**Comment by EliasGabr** [comment]
@Lost-Entrepreneur439 could you please update the efi and close this issue, would be very nice of you. so it is fixed by default

**Comment by Lost-Entrepreneur439** [comment]
> @Lost-Entrepreneur439 could you please update the efi and close this issue, would be very nice of you. so it is fixed by default

This EFI is EOL, as my T480s is broken.
